"""criar tabela textos

Revision ID: 42ed461535e8
Revises: 01af7998b8ec
Create Date: 2025-05-29 17:46:54.851042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ed461535e8'
down_revision: Union[str, None] = '01af7998b8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'textos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('caso_id', sa.UUID(), nullable=False),
        sa.Column('conteudo', sa.TEXT(), nullable=False),
        sa.Column('data_envio', sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('textos')
    # ### end Alembic commands ###
